on:
  push:
    branches:
      - main
    paths:
      - 'test/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
  call:
    needs: build
    uses: shristi-khandelwal/test/.github/workflows/test.yaml@main
